export const CONFIRMATION_QUEUE_GET = 'CONFIRMATION_QUEUE_GET';
export const CONFIRMATION_QUEUE_GET_SUCCEEDED = 'CONFIRMATION_QUEUE_GET_SUCCESSFUL';
export const CONFIRMATION_QUEUE_GET_FAILED = 'CONFIRMATION_QUEUE_GET_UNSUCCESSFUL';

export const CONFIRMATION_QUEUE_ADD = 'CONFIRMATION_QUEUE_ADD';
export const CONFIRMATION_QUEUE_ADD_SUCCEEDED = 'CONFIRMATION_QUEUE_ADD_SUCCESSFUL';
export const CONFIRMATION_QUEUE_ADD_FAILED = 'CONFIRMATION_QUEUE_ADD_UNSUCCESSFUL';

export const CONFIRMATION_QUEUE_REMOVE = 'CONFIRMATION_QUEUE_REMOVE';
export const CONFIRMATION_QUEUE_REMOVE_SUCCEEDED = 'CONFIRMATION_QUEUE_REMOVE_SUCCEEDED';
export const CONFIRMATION_QUEUE_REMOVE_FAILED = 'CONFIRMATION_QUEUE_REMOVE_FAILED';

export function getConfirmationQueue(node) {
  return {
    type: CONFIRMATION_QUEUE_GET,
    node,
  };
}

export function addBlojToConfirmationQueue(bloj, node) {
  return {
    type: CONFIRMATION_QUEUE_ADD,
    node,
    bloj,
  };
}

export function removeBlojFromConfirmationQueue(bloj, node) {
  return {
    type: CONFIRMATION_QUEUE_REMOVE,
    node,
    bloj,
  };
}